### ISSUE TITLE
Reporte Practica Architec

### ISSUE THREAD

**Issue by CxrlosMX** [SistemasTecTlaxiaco/practica-architect-CxrlosMX#1]
[Reporte Practica Architec.pdf](https://github.com/SistemasTecTlaxiaco/practica-architect-CxrlosMX/files/7172877/Reporte.Practica.Architec.pdf)

**Comment by Rmz-Rigo** [comment]
CALIFICACION: 19/20

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado.
